default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: kuoadmin
  password: KK1234765
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: kuo_development
test:
  <<: *default
  database: kuo_test
production:
  <<: *default
  database: kuo_production
  username: kuo
  password: <%= ENV['KUO_DATABASE_PASSWORD'] %>
