# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f4a57d65e026de339b2ba50ae05bdb81a4469d8a5a3906b5a8c7b31d874aa2238bc756bdec28cfcdf277ac1cc27c57315c06a21356f639c76cb580ccf835ff6

test:
  secret_key_base: d0c09145413e5072f03b7ff4ec078cc63e4371a2d33abd85ff84aa6e928fe46cfbbbcce9ddabfade2ea3bcdadf248ef0cea4c3da8729d187c3dcf62e63348c3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
